-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.Attachments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  url text NOT NULL,
  name text,
  size integer,
  type text NOT NULL,
  message_id uuid NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT Attachments_pkey PRIMARY KEY (id),
  CONSTRAINT Attachments_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.Messages(id)
);
CREATE TABLE public.Matches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  student_id uuid NOT NULL,
  client_id uuid NOT NULL,
  project_id uuid NOT NULL,
  student_swipe boolean,
  client_swipe boolean,
  matched boolean NOT NULL DEFAULT false,
  status USER-DEFINED,
  payment_status text,
  is_replacement boolean NOT NULL DEFAULT false,
  replacement_reason text,
  chatroom_id uuid NOT NULL DEFAULT gen_random_uuid(),
  student_rating numeric,
  client_rating numeric,
  student_feedback text,
  client_feedback text,
  CONSTRAINT Matches_pkey PRIMARY KEY (id, chatroom_id),
  CONSTRAINT Matches_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT Matches_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id),
  CONSTRAINT Matches_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.student_profiles(id)
);
CREATE TABLE public.Messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  text text,
  chatroom_id uuid NOT NULL,
  sender_id uuid,
  system boolean NOT NULL DEFAULT false,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT Messages_pkey PRIMARY KEY (id)
);
CREATE TABLE public.clients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text,
  email text UNIQUE,
  company_name text,
  company_website text,
  verified boolean DEFAULT false,
  profileimage text,
  industry text,
  location text,
  rating numeric,
  whyworkforus text,
  reviewscount integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT clients_pkey PRIMARY KEY (id)
);
CREATE TABLE public.projects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clientid uuid,
  title text NOT NULL,
  description text,
  topics ARRAY DEFAULT '{}'::text[],
  price numeric,
  duration text,
  perks ARRAY DEFAULT '{}'::text[],
  deliverables ARRAY DEFAULT '{}'::text[],
  applicants integer DEFAULT 0,
  status text DEFAULT 'open'::text,
  date_posted timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  required_hires integer NOT NULL DEFAULT 1,
  category text,
  CONSTRAINT projects_pkey PRIMARY KEY (id),
  CONSTRAINT projects_clientid_fkey FOREIGN KEY (clientid) REFERENCES public.clients(id)
);
CREATE TABLE public.student_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  category text,
  jobtitle text,
  description text,
  skills ARRAY,
  projects ARRAY,
  experience ARRAY,
  github text,
  linkedin text,
  awards ARRAY,
  resumeurl text,
  profileimage text,
  rating double precision,
  projectscompleted integer DEFAULT 0,
  isdoingproject boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  name text,
  vettingId uuid,
  authId uuid,
  CONSTRAINT student_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT student_profiles_user_id_fkey1 FOREIGN KEY (user_id) REFERENCES public.vettingapplications(id),
  CONSTRAINT student_profiles_vettingId_fkey FOREIGN KEY (vettingId) REFERENCES public.vettingapplications(id),
  CONSTRAINT student_profiles_authId_fkey FOREIGN KEY (authId) REFERENCES auth.users(id)
);
CREATE TABLE public.vettingapplications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category text,
  name text,
  email text NOT NULL UNIQUE,
  college text,
  dob date,
  cgpa numeric,
  year text,
  linkedin text,
  github text,
  location text,
  awards text,
  skills ARRAY NOT NULL,
  resume text,
  transcript text,
  studentId text,
  isComplete boolean DEFAULT false,
  createdAt timestamp with time zone DEFAULT now(),
  status text DEFAULT '''not_completed''::text'::text,
  currentStage numeric DEFAULT '1'::numeric,
  selectedProjectSanityId text,
  videoLink text,
  otherLinks text,
  projectDeadline timestamp with time zone,
  phone text,
  collegeEmail text,
  degree text,
  branch text,
  projects text,
  CONSTRAINT vettingapplications_pkey PRIMARY KEY (id)
);